### PR TITLE
Migrate to official openai~=1.2

### PR DESCRIPTION
**Pull request by iBug**

### CODE REVIEW

**Comment by zzh1996** [comment]
@iBug 
1. The new version of the OpenAI library includes an automatic retry feature. We should set `max_retries=0` to avoid the issue of double-layered retries.
2. We need to fix the bug at [[link]](https://github.com/zzh1996/chatgpt-telegram-bot/commit/e5d9e3e9422195820a075abb8fe89d30dcef4937). Otherwise, the HTTP connection pool will be exhausted after 100 requests, causing it to become unusable thereafter.
3. Although it won't make a substantial difference, I still prefer to use `is not None` for a more rigorous evaluation of the results returned in the stream, rather than the current approach of directly converting to a boolean type.
4. OpenAI's library does not strictly adhere to Semantic Versioning. PATCH versions are not just backward compatible bug fixes, so I'd like to lock down an exact version.
5. The examples in the official Python Docker documentation use the `pip` command rather than the `pip3` command. Please explain why this change is necessary.

**Comment by iBug** [comment]
Points 1-4 have been fixed. For point 5, `python` and `pip` have historically been associated with Python 2 on Unix platforms. Although this should not be the case for a pinned-down Docker container, I have *never* used `python` or `pip` to refer to Python 3.x. This is more a personal preference so I can revert this change at your request.

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[Claim Now](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by aatharvauti** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
dhelbegor, @LetmeBX, @wakiyamap, @NORMANCOMICS, @aka2882aka, @tyoc213, @BSathvik, @ozgrakkurt, @rymnc, @casey-barr, @ekreutz, @kfastov, @0x0elliot, @Hugoo, @0xfourzerofour, @ant4g0nist, @nochiel, @ivan-kyu, @NiteeshPutla, @SphereDonout

**Comment by zzh1996** [comment]
The issue addressed by this pull request has already been resolved long ago, so it will be closed.

**Pull request closed without merging**
